robots:
  - name: tb1
    is_master: false
    name_master: limo1
    has_camera: true
    has_max_time: false
    duration_max_time: 0.0
    use_camera: true
    pose_goal_1:
      x: -2.3
      y: -8.5
      z: 0.01
      yaw: 0.0
    pose_goal_2:
      x: 6.0
      y: 2.2
      z: 0.01
      yaw: 3.1416
    pose_goal_3:
      x: 1.8
      y: 9.5
      z: 0.01
      yaw: -1.5708
  - name: tb2
    is_master: false
    name_master: limo1
    has_camera: false
    has_max_time: true
    duration_max_time: 2.6
    use_camera: false
    pose_goal_1:
      x: 0.0
      y: 5.2
      z: 0.01
      yaw: 3.1416
    pose_goal_2:
      x: -0.1
      y: 2.8
      z: 0.01
      yaw: 3.1416
    pose_goal_3:
      x: 0.2
      y: -0.1
      z: 0.01
      yaw: 0.0
    pose_goal_4:
      x: -4.0
      y: 9.0
      z: 0.01
      yaw: 0.0
  - name: limo1
    is_master: true
    has_camera: true
    same_time_task: false
  - name: limo2
    is_master: false
    name_master: limo1
    has_camera: true
    has_max_time: false
    duration_max_time: 0.0
    use_camera: true
    pose_goal_1:
      x: 2.2
      y: 0.6
      z: 0.01
      yaw: 3.1416
    pose_goal_2:
      x: 2.2
      y: -3.1
      z: 0.01
      yaw: 3.1416
    pose_goal_3:
      x: 2.2
      y: -6.8
      z: 0.01
      yaw: 3.1416
