robots:
  - name: tb1
    is_master: false
    name_master: tb3
    duration_max_time: 0.5
    pose_goal_1:
      x: 4.0
      y: 1.0
      z: 0.01
      yaw: 0.0
  - name: tb2
    is_master: false
    name_master: tb3
    duration_max_time: 0.5
    pose_goal_1:
      x: -6.5
      y: 2.0
      z: 0.01
      yaw: 0.0
  - name: tb3
    is_master: true
    same_time_task: false
    