robots:
  - name: diff500
    is_master: false
    name_master: mpo700
    has_camera: true
    has_max_time: false
    duration_max_time: 0.0
    use_camera: true
    pose_goal_1:
      x: 4.0
      y: 1.0
      z: 0.01
      yaw: 0.0
  - name: omni500
    is_master: false
    name_master: mpo700
    has_camera: false
    has_max_time: true
    duration_max_time: 1.3
    use_camera: false
    pose_goal_1:
      x: -1.5
      y: 4.0
      z: 0.01
      yaw: 0.0
    pose_goal_2:
      x: -4.0
      y: 2.0
      z: 0.01
      yaw: 0.0
    pose_goal_3:
      x: -1.5
      y: 0.5
      z: 0.01
      yaw: 0.0
  - name: mpo700
    is_master: true
    has_camera: true
    same_time_task: false
    