robots:
  - name: diff500
    is_master: false
    name_master: mpo700_1
    has_camera: false
    has_max_time: false
    duration_max_time: 0.0
    use_camera: false
    pose_goal_1:
      x: 2.2
      y: -6.75
      z: 0.01
      yaw: 3.1416
    pose_goal_2:
      x: 2.2
      y: -3.0
      z: 0.01
      yaw: 3.1416
    pose_goal_3:
      x: 2.2
      y: 0.5
      z: 0.01
      yaw: 3.1416
  - name: mpo700_2
    is_master: false
    name_master: mpo700_1
    has_camera: false
    has_max_time: false
    duration_max_time: 0.0
    use_camera: false
    pose_goal_1:
      x: 2.2
      y: -8.75
      z: 0.01
      yaw: 3.1416
    pose_goal_2:
      x: 2.2
      y: -4.75
      z: 0.01
      yaw: 3.1416
    pose_goal_3:
      x: 2.2
      y: -1.25
      z: 0.01
      yaw: 3.1416
  - name: mpo700_1
    is_master: true
    has_camera: false
    same_time_task: false
